---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bootsprings
  labels:
    app: bootsprings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bootsprings
  template:
    metadata:
      labels:
        app: bootsprings
    spec:
      containers:
        - name: bootsprings
          image: docker.io/phengbunath/bootsprings:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
